"""Build the narration for YouTube video 1 with the Arabic piper voice.
Usage: python3 yt1_tts.py <piper_model_dir> <out_dir> <timing_ts_path>
Writes <out_dir>/narration_raw.wav, per-sentence wavs, and a TS timing file."""
import json
import os
import sys
import wave

import numpy as np
import sherpa_onnx

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from yt1_script import SCRIPT  # noqa: E402

M, out, ts_path = sys.argv[1], sys.argv[2], sys.argv[3]
os.makedirs(out, exist_ok=True)
cfg = sherpa_onnx.OfflineTtsConfig(
    model=sherpa_onnx.OfflineTtsModelConfig(
        vits=sherpa_onnx.OfflineTtsVitsModelConfig(
            model=f"{M}/ar_JO-kareem-medium.onnx", tokens=f"{M}/tokens.txt", data_dir=f"{M}/espeak-ng-data"
        ),
        num_threads=4,
    )
)
tts = sherpa_onnx.OfflineTts(cfg)

LEAD_IN = 2.2  # title + riser before the first sentence
GAP = 0.38  # between sentences
SECTION_GAP = 1.15  # room for the MJ transition between sections
TAIL = 4.0  # end card

pieces = []
timing = []
t = LEAD_IN
sr = None
prev_section = None
for i, (section, plain, voc) in enumerate(SCRIPT):
    a = tts.generate(voc, sid=0, speed=0.93)
    sr = a.sample_rate
    x = np.array(a.samples, dtype=np.float32)
    # trim leading / trailing near-silence
    idx = np.where(np.abs(x) > 0.01)[0]
    x = x[max(0, idx[0] - int(0.03 * sr)) : idx[-1] + int(0.06 * sr)]
    if prev_section is not None:
        t += SECTION_GAP if section != prev_section else GAP
    timing.append({"i": i, "section": section, "text": plain, "start": round(t, 3), "end": round(t + len(x) / sr, 3)})
    pieces.append((t, x))
    w = wave.open(os.path.join(out, f"s{i:02d}.wav"), "wb")
    w.setnchannels(1)
    w.setsampwidth(2)
    w.setframerate(sr)
    w.writeframes((np.clip(x, -1, 1) * 32767).astype(np.int16).tobytes())
    w.close()
    t += len(x) / sr
    prev_section = section

total = t + TAIL
buf = np.zeros(int(total * sr) + 1, dtype=np.float32)
for start, x in pieces:
    i0 = int(start * sr)
    buf[i0 : i0 + len(x)] += x
w = wave.open(os.path.join(out, "narration_raw.wav"), "wb")
w.setnchannels(1)
w.setsampwidth(2)
w.setframerate(sr)
w.writeframes((np.clip(buf, -1, 1) * 32767).astype(np.int16).tobytes())
w.close()

with open(ts_path, "w") as f:
    f.write("// Generated by scripts/yt1_tts.py - narration timing (seconds).\n")
    f.write(f"export const YT1_DURATION = {round(total, 3)};\n")
    f.write("export type Line = { i: number; section: string; text: string; start: number; end: number };\n")
    f.write("export const LINES: Line[] = " + json.dumps(timing, ensure_ascii=False, indent=2) + ";\n")
print("total", round(total, 2), "s,", len(timing), "lines")
